<Command>
    size_hint_y: None
    pos_hint: {"right": .98}
    height: self.texture_size[1]
    paddding: 15, 20
    theme_text_color: "Custom"
    text_color: 1,1,1,1
    canvas.before:
        Color:
            rgb: app.theme_cls.primary_color
            #rgb: (1, 170/255, 23/255,1)
        RoundedRectangle:
            size: self.width, self.height
            pos: self.pos
<Response>
    size_hint_y: None
    pos_hint: {"x": .03}
    height: self.texture_size[1]
    paddding: 15, 20
    canvas.before:
        Color:
            rgb: (222/255,222/255,222/255,1)
        RoundedRectangle:
            size: self.width, self.height
            pos: self.pos
<Time>
    size_hint_y: None
    height: self.texture_size[1]
    canvas.before:
        Color:
            rgb: (1,1,1,1)

MDScreen:   
    name: "hist"
    chat_list: chat_list
    scroll: scroll
    on_enter:
        app.load_his()
    MDFloatLayout:
        MDLabel:
            text: "HISTORY"
            pos_hint: {"center_y": .94}
            halign: "center"
        ScrollView:
            id: scroll
            size_hint_y: .9
            pos_hint: {"x": 0, "y": .025}
            do_sroll_x: False
            do_sroll_y: True
            MDBoxLayout:
                id: chat_list
                orientation: 'vertical'
                size: (root.width, root.height)
                height: self.minimum_height
                size_hint: None, None
                pos_hint: {'top': 10}
                cols: 1
                spacing: 5

    MDRectangleFlatButton:
        text: "Back"
        pos_hint:{"right":0.2,"top": .98}
        on_release:
            app.to_main()
            app.clear("hist")