MDScreen:
    name: "login"
    on_leave:
        mail.text = ""
        passw.text = ""
    MDFloatLayout:
        Image:
            source: 'Logo.png'   
            size_hint_y: None
            pos_hint: {"center_x": .5, "center_y": .85}
            width: '150dp'
            allow_stretch: True

        MDTextField:
            id: mail
            size_hint_x: .85
            pos_hint: {"center_x": .5, "center_y": .57}
            hint_text: "Enter email"
            required: True
            mode: "rectangle"
            
        MDTextField:
            id: passw
            size_hint_x: .85
            pos_hint: {"center_x": .5, "center_y": .42}
            hint_text: "Enter password"
            required: True
            password: True
            mode: "rectangle"

        MDRectangleFlatButton:
            text: "Sign In"
            pos_hint: {"center_x": .5, "center_y": .15}
            on_release: 
                app.to_sign()

        MDRectangleFlatButton:
            text: "Login"
            pos_hint: {"center_x": .5, "center_y": .25}
            
            on_release:
                app.check_login(mail.text ,passw.text) if mail.text != "" and passw.text != ""  else app.message("Please do not leave the field blank !!!")

            
