MDScreen:
    name: "signin"
    on_leave:
        mail.text = ""
        passw.text = ""
        repass.text = ""
    MDRectangleFlatButton:
        text: "Back"
        pos_hint:{"right":0.2,"top": .98}
        on_release:
            app.to_login()

    MDFloatLayout:
        
        Image:
            source: 'Logo.png'   
            size_hint_y: None
            pos_hint: {"center_x": .5, "center_y": .85}
            width: 900
            allow_stretch: True

        MDTextField:
            id: mail
            size_hint_x: .85
            pos_hint: {"center_x": .5, "center_y": .55}
            hint_text: "Enter email"
            required: True
            mode: "rectangle"

        MDTextField:
            id: passw
            size_hint_x: .85
            pos_hint: {"center_x": .5, "center_y": .425}
            hint_text: "Enter password"
            required: True
            password: True
            mode: "rectangle"

        MDTextField:
            id: repass
            size_hint_x: .85
            pos_hint: {"center_x": .5, "center_y": .3}
            hint_text: "Enter password again"
            required: True
            password: True
            mode: "rectangle"

        MDRectangleFlatButton:
            text: "Sign In"
            pos_hint: {"center_x": .5, "center_y": .15}
            on_release:
                app.signin(mail.text ,passw.text, repass.text) if mail.text != "" and passw.text != "" and repass.text != "" else app.message("Please do not leave the field blank !!!")
                
